import '../ai/atlas_brain.dart';

/// Thin facade over AtlasBrain, kept in services/ so screens depend on a
/// stable service interface rather than the AI internals directly.
///
/// IMPORTANT — about connecting a *real* external AI model:
/// Right now Atlas's "intelligence" is 100% local: rule-based parsing +
/// statistics over your own task history (see lib/ai/*). This is what
/// lets the app be free, private, and fully offline.
///
/// If you later want Atlas's chat replies to be generated by a real large
/// language model (e.g. Claude) instead of the local rules, that requires:
///   1. An API key from an AI provider (this has a per-usage cost).
///   2. A backend endpoint you control (never call a paid AI API directly
///      from the phone with an embedded key — anyone could extract it).
///   3. Replacing the body of [generateReply] below with an HTTP call to
///      that backend, then falling back to AtlasBrain locally if the
///      network call fails (important for the app's offline mode).
///
/// None of that is required for the app to work today — this class works
/// fully offline as-is.
class AIService {
  final AtlasBrain _brain;
  AIService({AtlasBrain? brain}) : _brain = brain ?? AtlasBrain();

  AtlasBrain get brain => _brain;

  Future<AtlasReply> generateReply(
    String userMessage, {
    required DateTime today,
    required String wakeTime,
    required String sleepTime,
  }) {
    // Local-only implementation. Swap this call for a remote one later
    // if/when a paid external AI backend is set up.
    return _brain.respondTo(
      userMessage,
      today: today,
      wakeTime: wakeTime,
      sleepTime: sleepTime,
    );
  }
}
